### ISSUE TITLE
你好，我想修改下插件

### ISSUE THREAD

**Issue by niuzheng168** [tinymins/MY#1]
你好！我是一名玩家兼程序员。
首先感谢你的插件，真的很好用！
我也阅读了你的源代码，想做些改动仅供我自己使用，但是在\JX3\bin\zhcn\interface\MY\MY_Recount\src 类似的目录下我发现lua文件已经不是readable script了，好像变成了binary文件，请问我更改的代码需要做什么样的操作才能被剑网3系统接受呢？我觉得LUA应该不需要编译啊。

顺便说下我在做的东西。我想把战斗数据全存下来，dump到本地，然后训练一些model来分析DPS

**Comment by tinymins** [comment]
官方有认证的，源码要认证了才能在客户端使用，所以……
说起来 dump下来，如果只是dps统计的话，插件有提供保存数据的选项啊

**Comment by niuzheng168** [comment]
是么？我看下，我只发现有个功能是离线保存，所以肯定是保存下来了的。但是我看了下保存的文件，好像还是binary的。。。。我晚上回去再确认下。

感谢你的回复
