### ISSUE TITLE
聊天过滤无法启用且不能添加关键字

### ISSUE THREAD

**Issue by inkedawn** [tinymins/MY#14]

**Comment by tinymins** [comment]
看微博置顶或者看提交记录…… https://github.com/tinymins/MY/commit/56b9ff0f07e85a91eb98002827c47d1b20ed1901 
![image](https://user-images.githubusercontent.com/1808990/33592454-27728d0e-d9c6-11e7-9cd1-5bf21a49bde0.png)
什么都不看就提交那可能每个人来一下这里就满了
