### ISSUE TITLE
关于奇遇记录上传

### ISSUE THREAD

**Issue by inkedawn** [tinymins/MY#16]
想必你已经知道了关于贴吧的事
虽然他大部分但是断章取义或者脑补强行扯淡，但是插件确实有一点不好就是：关于奇遇触发记录的上传，用户的确不知情

建议增加选项，供用户选择是否开启，以免被人抓尾巴说侵犯用户隐私

**Comment by tinymins** [comment]
好

**Comment by inkedawn** [comment]
辛苦了
