### ISSUE TITLE
焦点列表血量是否可以使用亿单位

### ISSUE THREAD

**Issue by NanGongBo** [tinymins/MY#18]
![image](https://user-images.githubusercontent.com/31374823/41477738-cda3ac58-70f7-11e8-9457-6ceef1b6ff3a.png)

**Comment by tinymins** [comment]
![image](https://user-images.githubusercontent.com/1808990/41605951-2a314032-7415-11e8-841e-bb88f85b2026.png)
测试完成 等待版本更新
