### ISSUE TITLE
战斗统计 - 部分人的dps 在面板显示 与 发布到聊天 不符合

### ISSUE THREAD

**Issue by pinelliar** [tinymins/MY#20]
如图，第1名、第9名、第11名发布在聊天频道的显示，无论是有效数值与总数值都与面板显示不相符，并且均为偏低

![image](https://user-images.githubusercontent.com/10476912/43684171-c4c8d5ec-98cd-11e8-9280-5c8b6277bb3d.png)
![image](https://user-images.githubusercontent.com/10476912/43684176-ebf731f4-98cd-11e8-884a-f0d54041a32e.png)
![image](https://user-images.githubusercontent.com/10476912/43684180-fa1ab2c4-98cd-11e8-9841-64196751312a.png)

如图，第4名、第14名、第17名、第19名也存在此问题
![image](https://user-images.githubusercontent.com/10476912/43684211-5d3bdfae-98ce-11e8-94cd-57d4d5922e42.png)
![image](https://user-images.githubusercontent.com/10476912/43684195-2bac5c66-98ce-11e8-98cd-688502ad3cd0.png)
![image](https://user-images.githubusercontent.com/10476912/43684201-3814ff58-98ce-11e8-9ee5-115722cba8cf.png)
![image](https://user-images.githubusercontent.com/10476912/43684205-44fefd40-98ce-11e8-97a5-c71c2edfa380.png)

附上战斗记录文件fight_recount_log.jx3dat

[fight_recount_log.zip](https://github.com/tinymins/MY/files/2260140/fight_recount_log.zip)

**Comment by tinymins** [comment]
@inkedawn 知道了，暂离时间没有考虑到，我晚上回去找时间看下，感谢
