### ISSUE TITLE
LUA TABLE表结构解析为JSON后与描述不符

### ISSUE THREAD

**Issue by saksim** [tinymins/MY#23]
背景： 
    开启茗伊保存数据功能后，在读取保存数据时，通过[slpp](https://github.com/SirAnthony/slpp)解析lua table 数据为 json数据后，数据结构与[你们官方数据结构](https://github.com/tinymins/MY/wiki/MY-Recount-Data-Structure) 的结构有所出入

疑问：是否有新的数据结构体

**Comment by saksim** [comment]
![image](https://user-images.githubusercontent.com/25615860/102467237-0563f200-408b-11eb-85af-22e43abfe587.png)

**Comment by tinymins** [comment]
有原始数据文件吗，你划第二个红框的主键理论上应当出现在一个字表中，我想确认下是我的问题还是你提到的LUA表解析器有问题。

**Comment by saksim** [comment]
OK,数据如下：
[data.tar.gz](https://github.com/tinymins/MY/files/5708971/data.tar.gz)

**Comment by tinymins** [comment]
解了一下，确实，你那个解析器好像有问题喔
[formatted.jx3dat.tar.gz](https://github.com/tinymins/MY/files/5709101/formatted.jx3dat.tar.gz)

**Comment by tinymins** [comment]
如果你用 python 的话，可以试试朋友写的[这个luadata工具](https://github.com/leafvmaple/luadata)

**Comment by tinymins** [comment]
![image](https://user-images.githubusercontent.com/1808990/102489128-05261f80-40a8-11eb-896a-f9eabcc4ae51.png)
有12喔

![image](https://user-images.githubusercontent.com/1808990/102489169-12430e80-40a8-11eb-8e00-f641909d3763.png)
主体结构中也没有你截图的主键喔

**Comment by saksim** [comment]
OK, 非常感谢作者的帮助~我去尝试一下
