### ISSUE TITLE
【新插件】动态测距

### ISSUE THREAD

**Issue by iRuxu** [tinymins/MY#29]
目前需要选中一个目标，才能知道自己和指定目标的距离

是否可以有一个工具，按一下后，鼠标指向的坐标，即可显示自己当前与指针位置之间的距离。

应用：
+ 提前站位，不一定要等目标过去

具体距离：
+ 猿飞，使用奶花保人，奶花需离光柱一定的距离才能保住。但光柱位置不一定有人。

**Comment by tinymins** [comment]
这有点难，光柱一般来说是个隐藏NPC或者DOODAD，试试看能不能从焦点列表找到？
