### ISSUE TITLE
聊天监控的导出或者增加历史记录长度

### ISSUE THREAD

**Issue by zengluyang** [tinymins/MY#4]
你好，我是一名程序员兼玩家，最近在开团过程中有一个需要增加聊天监控记录条数的需求（仙侣老三判断哪些人没停手导致灭团），不知道有没有办法改一些配置文件实现，或者增加这么一个功能，或者能让对战斗记录的监控导出到硬盘上某个文本文件。
类似这样，只是记录的历史记录长度不够，无法找到犯错的玩家
![image](https://cloud.githubusercontent.com/assets/1927890/11570096/60685116-9a30-11e5-89ab-7fb07975d72f.png)

https://github.com/tinymins/MY/blob/master/ChatMonitor/src/MY_ChatMonitor.lua#L26
是否可以考虑添加一个UI让玩家可以设置的这个`MY_ChatMonitor.nMaxRecord`数值？

最后，感谢对剑三插件的开发！

**Comment by tinymins** [comment]
将会在下次版本发布[ aaead1629f1c9e29d23eb356d790826960c3a066 ]，感谢提交建议=w=
