### ISSUE TITLE
V62 以後的 DB 如何創建出來?  

### ISSUE THREAD

**Issue by savinna** [tinymins/MY#6]
V62 以後的 DB 如何創建出來?  
系統找不到每一個 db files

**Comment by savinna** [comment]
是因為 windows10 的權限關係嗎?  所以 DB 檔案都無法產生?

**Comment by Webster-jx3** [comment]
暂时还不支持SQLite3 等一下吧 现在这属于dev 实验阶段 应该快了

**Comment by Webster-jx3** [comment]
暂时还不支持SQLite3 等一下吧 现在这属于dev 实验阶段 应该快了

**Comment by savinna** [comment]
謝謝,因為台服巴哈,已經有人發表 V62 V63 了,可是發現那些使用  SQLite3  的功能都出現問題!
目前只有 V61 舊版架構正常~

**Comment by savinna** [comment]
SQLite3 結構,取代 txt 結構,效能會快不少,減少檔案無限的產生,減少 IO 的寫入讀取!
期待新的  SQLite3  結構的完成 >_<

**Comment by Webster-jx3** [comment]
暂时不要更新新版本，SQLite3也是迫于无奈，毕竟文件存储读取的IO的确有很严重的性能问题，少的时候区别不大，多的时候非常严重，名一弄SQLite3也有大半年了，应该快好了。

**Comment by savinna** [comment]
因為我本身也是 coder , 我有試著 SQLite3 create DB , create table , 不過還是不行用 >_<
看來只能自行找些可以 update 的部分,手動去 update V61 了~
V61 實在太舊了,霸刀出了之後,少了很多東西!

**Comment by savinna** [comment]
菊总....那 JH 的 dev master 可以直接用嗎?  會有甚麼問題嗎?

**Comment by tinymins** [comment]
@savinna 方便看一下Log吗？我看看是接口还没有同步到台服，还是因为繁体编码问题导致连接到数据库失败？谢=w=。

**Comment by savinna** [comment]
@tinymins 有方便聯絡 QQ ?  還是微信 ?  還是其他可以即時溝通工具?
我一開始也是覺得編碼問題,我有轉過 Big5 , 還是 DB 也自己手動建立出來,可是還是 cannot connect database!

**Comment by tinymins** [comment]
@savinna 可以QQ 我加你下？

**Comment by savinna** [comment]
@tinymins   QQ: 3248473267

**Comment by tinymins** [comment]
Fixed
