### ISSUE TITLE
12月15号更新之后不能监控系统频道的喊话了

### ISSUE THREAD

**Issue by Dearest** [tinymins/MY#7]
eg： 在聊天监控里输入 “宝马”， 只监控系统频道。在之前是可以监控到刷马的。今天更新后就监控不到了

**Comment by tinymins** [comment]
![image](https://cloud.githubusercontent.com/assets/1808990/21219964/cb923cfa-c2f1-11e6-9999-1aca975133f4.png)
测试可以使用 插件更新没有禁用掉之前的插件导致的 等待下次客户端更新修复
