### ISSUE TITLE
1215更新后出现莫名卡顿

### ISSUE THREAD

**Issue by iiiplus** [tinymins/MY#8]
1215更新后，加载茗伊插件集中的聊天记录子插件会导致游戏整体KGUI卡顿。一般涉及到的是聊天框中出现各种提示信息时会严重卡顿，如交任务时出现的信息提示、帮会成员对新入帮成员欢迎语刷屏、击杀与被击杀时出现的喊话等等。不知是与其他插件冲突，还是SQLite3的相关问题。因为日志中出现大量SQLite3的错误提示。
        认识的亲友中有很多人出现这种问题，所用操作系统从win7-win10均有分布。显卡、IO和其他硬件信息没统计过。希望作者有时间能看一下。么么哒辛苦了。

**Comment by tinymins** [comment]
求截取一份错误提示的Log

**Comment by iiiplus** [comment]
只加载了茗依的聊天记录插件。zip打包无法上传，只能百度云了。https://pan.baidu.com/s/1dE13dbb

**Comment by tinymins** [comment]
我看完了 没有我的插件相关的任何LOG啊 全是DX11报错 你用DX9登录试试？

**Comment by tinymins** [comment]
具体来说是 在插件加载之前 你的客户端已经和服务器断开了连接 原因不明但是看到大量DX11报错

**Comment by tinymins** [comment]
又看了一遍 你的资源坏的很严重啊 UserShader都跪了 你要先修复下客户端 然后再看看有没有问题
